"""Checkpoint inventory: fetch the ladder, then measure what actually arrived.

The x-axis of this study is bits per weight, and the published bpw table is not
it. Those tables describe a quant type in the abstract; what a given file spends
depends on the model's tensor shapes and on how the publisher treated the
embedding and output layers, which for Qwen3-8B is a 151936 x 4096 matrix at
each end -- 15% of the parameters, routinely left at higher precision than the
name suggests. The gap is largest exactly where it matters: Q2_K is 3.21 bpw for
this model, not the 2.96 the table gives, and IQ2_M is 2.98 rather than 2.70.

So the value that gets plotted is `file_bytes * 8 / n_params`, taken from the
file on disk. `ladder.yaml` carries the same quantity computed from the size
HuggingFace advertises, which makes --verify an integrity check on the
download: a rung whose bytes disagree with the bytes the hub promised is a
truncated or renamed file, not a surprising checkpoint.

    python -m ladder.models --list
    python -m ladder.models --emit-download     # writes scripts/download_models.sh
    python -m ladder.models --verify            # writes models.lock.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from ladder.server import CONFIG_DIR, PACKAGE_ROOT, QWEN3_8B_PARAMS, SCRIPTS_DIR, LadderConfig, load_configs

LOCK_PATH = PACKAGE_ROOT / "models.lock.json"

# `bpw_nominal` in the config is itself measured -- from the size HuggingFace
# reports for the file -- so this compares a measurement against a measurement
# and can be tight. It is an integrity check on the download, not a check on
# the published tables: it fires on a truncated file, a renamed quant, or a
# repo that re-uploaded a rung at a different width.
BPW_TOLERANCE = 0.15


def measured_bpw(path: Path, n_params: int = QWEN3_8B_PARAMS) -> float | None:
    if not path.exists():
        return None
    return path.stat().st_size * 8.0 / n_params


def render_download_script(configs: dict[str, LadderConfig]) -> str:
    """One `hf download` per rung, into the shared model directory.

    Emitted rather than run, for the same reason bench emits its serve scripts:
    the command that produced a measurement should sit in version control next
    to the measurement, not in somebody's shell history.
    """
    model_dir = next(iter(configs.values())).model_dir
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by ladder.models. Do not edit by hand; edit config/ladder.yaml.",
        "#",
        "# Pulls every rung of the GGUF ladder. ~147 GiB in total, dominated by",
        "# the BF16 anchor at 15.3 GiB; the sub-3-bpw rungs are 2-3 GiB each.",
        "#",
        "# Re-running is cheap: the HuggingFace cache skips anything already local.",
        "set -euo pipefail",
        "",
        f'MODEL_DIR="${{MODEL_DIR:-{model_dir}}}"',
        'mkdir -p "$MODEL_DIR"',
        "",
    ]
    for cfg in configs.values():
        lines += [
            f"# {cfg.id}: {cfg.quant_type}, {cfg.bpw_nominal} bpw  [{cfg.group}]",
            f'hf download {cfg.repo} {cfg.gguf_file} \\',
            f'    --local-dir "$MODEL_DIR"',
            "",
        ]
    lines += [
        "echo",
        'echo "Downloaded. Now confirm sizes and measured bpw:"',
        'echo "  python -m ladder.models --verify"',
        "",
    ]
    return "\n".join(lines)


def inventory(configs: dict[str, LadderConfig]) -> list[dict]:
    rows = []
    for cfg in configs.values():
        path = Path(cfg.model_dir) / cfg.gguf_file
        bpw = measured_bpw(path)
        row = {
            "config_id": cfg.id,
            "group": cfg.group,
            "family": cfg.family,
            "quant_type": cfg.quant_type,
            "repo": cfg.repo,
            "gguf_file": cfg.gguf_file,
            "bpw_nominal": cfg.bpw_nominal,
            "present": bpw is not None,
            "size_bytes": path.stat().st_size if bpw is not None else None,
            "bpw_measured": round(bpw, 3) if bpw is not None else None,
        }
        if bpw is not None:
            row["bpw_matches_nominal"] = abs(bpw - cfg.bpw_nominal) <= BPW_TOLERANCE
        rows.append(row)
    return rows


def _print_table(rows: list[dict]) -> None:
    header = (
        f"{'rung':14s} {'group':16s} {'fam':7s} {'quant':12s} "
        f"{'nominal':>8s} {'measured':>9s} {'GiB':>7s}  file"
    )
    print(header)
    print("-" * len(header))

    total_bytes = 0
    for row in rows:
        size = row["size_bytes"]
        bpw = row["bpw_measured"]
        total_bytes += size or 0
        measured = f"{bpw:.2f}" if bpw is not None else "-"
        gib = f"{size / 2**30:.1f}" if size else "-"
        # A rung whose measured width is far from its published one is flagged
        # inline as well as in the summary, so a full-table read catches it.
        flag = "" if row.get("bpw_matches_nominal", True) else "  <- check"
        print(
            f"{row['config_id']:14s} {row['group']:16s} {row['family']:7s} "
            f"{row['quant_type']:12s} {row['bpw_nominal']:8.2f} {measured:>9s} "
            f"{gib:>7s}  {row['gguf_file']}{flag}"
        )

    present = sum(1 for r in rows if r["present"])
    print(f"\n{present}/{len(rows)} present, {total_bytes / 2**30:.1f} GiB on disk")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--list", action="store_true", help="Print the ladder and exit")
    parser.add_argument(
        "--emit-download",
        action="store_true",
        help="Write scripts/download_models.sh and exit",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Check every file is present, measure bpw, write models.lock.json",
    )
    parser.add_argument("--config", type=Path, default=CONFIG_DIR / "ladder.yaml")
    args = parser.parse_args()

    configs = load_configs(args.config)

    if args.emit_download:
        SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
        path = SCRIPTS_DIR / "download_models.sh"
        path.write_text(render_download_script(configs), encoding="utf-8", newline="\n")
        print(f"wrote {path}")
        return 0

    rows = inventory(configs)

    if args.list or not args.verify:
        _print_table(rows)
        if not args.verify:
            missing = [r for r in rows if not r["present"]]
            if missing:
                print(
                    f"\n{len(missing)} of {len(rows)} file(s) not on disk. "
                    f"Run --emit-download, then the script, then --verify.",
                    file=sys.stderr,
                )
        return 0

    # --verify
    _print_table(rows)
    missing = [r["config_id"] for r in rows if not r["present"]]
    mismatched = [
        r["config_id"]
        for r in rows
        if r["present"] and not r.get("bpw_matches_nominal", True)
    ]

    LOCK_PATH.write_text(
        json.dumps({"n_params": QWEN3_8B_PARAMS, "rungs": rows}, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"\nwrote {LOCK_PATH}")

    if missing:
        print(f"\nmissing: {', '.join(missing)}", file=sys.stderr)
    if mismatched:
        # Not fatal, but it has exactly one likely cause worth naming.
        print(
            f"\nmeasured bpw is more than {BPW_TOLERANCE} from nominal for: "
            f"{', '.join(mismatched)}.\nUsually the published filename changed and "
            f"a different quant was fetched. Check the repo listing before "
            f"treating these as rungs.",
            file=sys.stderr,
        )
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
