#!/usr/bin/env bash
# Generated by ladder.models. Do not edit by hand; edit config/ladder.yaml.
#
# Pulls every rung of the GGUF ladder. ~147 GiB in total, dominated by
# the BF16 anchor at 15.3 GiB; the sub-3-bpw rungs are 2-3 GiB each.
#
# Re-running is cheap: the HuggingFace cache skips anything already local.
set -euo pipefail

MODEL_DIR="${MODEL_DIR:-./models/gguf}"
mkdir -p "$MODEL_DIR"

# bf16: BF16, 16.01 bpw  [anchor]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-bf16.gguf \
    --local-dir "$MODEL_DIR"

# q8_0: Q8_0, 8.51 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q8_0.gguf \
    --local-dir "$MODEL_DIR"

# q6_k_l: Q6_K_L, 6.86 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q6_K_L.gguf \
    --local-dir "$MODEL_DIR"

# q6_k: Q6_K, 6.57 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q6_K.gguf \
    --local-dir "$MODEL_DIR"

# q5_k_l: Q5_K_L, 6.09 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q5_K_L.gguf \
    --local-dir "$MODEL_DIR"

# q5_k_m: Q5_K_M, 5.72 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q5_K_M.gguf \
    --local-dir "$MODEL_DIR"

# q5_k_s: Q5_K_S, 5.59 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q5_K_S.gguf \
    --local-dir "$MODEL_DIR"

# q4_k_l: Q4_K_L, 5.36 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q4_K_L.gguf \
    --local-dir "$MODEL_DIR"

# q4_1: Q4_1, 5.13 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q4_1.gguf \
    --local-dir "$MODEL_DIR"

# q4_k_m: Q4_K_M, 4.91 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q4_K_M.gguf \
    --local-dir "$MODEL_DIR"

# q3_k_xl: Q3_K_XL, 4.86 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q3_K_XL.gguf \
    --local-dir "$MODEL_DIR"

# q4_k_s: Q4_K_S, 4.69 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q4_K_S.gguf \
    --local-dir "$MODEL_DIR"

# iq4_nl: IQ4_NL, 4.68 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-IQ4_NL.gguf \
    --local-dir "$MODEL_DIR"

# q4_0: Q4_0, 4.68 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q4_0.gguf \
    --local-dir "$MODEL_DIR"

# iq4_xs: IQ4_XS, 4.46 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-IQ4_XS.gguf \
    --local-dir "$MODEL_DIR"

# q3_k_l: Q3_K_L, 4.33 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q3_K_L.gguf \
    --local-dir "$MODEL_DIR"

# q3_k_m: Q3_K_M, 4.03 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q3_K_M.gguf \
    --local-dir "$MODEL_DIR"

# iq3_m: IQ3_M, 3.81 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-IQ3_M.gguf \
    --local-dir "$MODEL_DIR"

# q2_k_l: Q2_K_L, 3.8 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q2_K_L.gguf \
    --local-dir "$MODEL_DIR"

# q3_k_s: Q3_K_S, 3.68 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q3_K_S.gguf \
    --local-dir "$MODEL_DIR"

# iq3_xs: IQ3_XS, 3.54 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-IQ3_XS.gguf \
    --local-dir "$MODEL_DIR"

# iq3_xxs: IQ3_XXS, 3.29 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-IQ3_XXS.gguf \
    --local-dir "$MODEL_DIR"

# q2_k: Q2_K, 3.21 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-Q2_K.gguf \
    --local-dir "$MODEL_DIR"

# iq2_m: IQ2_M, 2.98 bpw  [ladder]
hf download bartowski/Qwen_Qwen3-8B-GGUF Qwen_Qwen3-8B-IQ2_M.gguf \
    --local-dir "$MODEL_DIR"

# ud_q4_k_xl: UD-Q4_K_XL, 5.02 bpw  [unsloth_dynamic]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-Q4_K_XL.gguf \
    --local-dir "$MODEL_DIR"

# ud_q3_k_xl: UD-Q3_K_XL, 4.21 bpw  [unsloth_dynamic]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-Q3_K_XL.gguf \
    --local-dir "$MODEL_DIR"

# ud_q2_k_xl: UD-Q2_K_XL, 3.42 bpw  [unsloth_dynamic]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-Q2_K_XL.gguf \
    --local-dir "$MODEL_DIR"

# ud_iq3_xxs: UD-IQ3_XXS, 3.33 bpw  [unsloth_dynamic]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-IQ3_XXS.gguf \
    --local-dir "$MODEL_DIR"

# ud_iq2_m: UD-IQ2_M, 3.04 bpw  [unsloth_dynamic]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-IQ2_M.gguf \
    --local-dir "$MODEL_DIR"

# ud_iq2_xxs: UD-IQ2_XXS, 2.54 bpw  [sub3_extension]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-IQ2_XXS.gguf \
    --local-dir "$MODEL_DIR"

# ud_iq1_m: UD-IQ1_M, 2.34 bpw  [sub3_extension]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-IQ1_M.gguf \
    --local-dir "$MODEL_DIR"

# ud_iq1_s: UD-IQ1_S, 2.22 bpw  [sub3_extension]
hf download unsloth/Qwen3-8B-GGUF Qwen3-8B-UD-IQ1_S.gguf \
    --local-dir "$MODEL_DIR"

echo
echo "Downloaded. Now confirm sizes and measured bpw:"
echo "  python -m ladder.models --verify"
