#!/usr/bin/env bash
# Generated by ladder.server. Do not edit by hand; edit config/ladder.yaml.
#
# Rung   : q4_k_s  (Qwen3-8B Q4_K_S)
# Quant  : Q4_K_S  (kquant, ~4.69 bpw nominal)
# Source : bartowski/Qwen_Qwen3-8B-GGUF :: Qwen_Qwen3-8B-Q4_K_S.gguf
# Group  : ladder
#
# --ctx-size is 8192 per slot x 8 slots = 65536.
# llama.cpp divides one context across --parallel slots, so the per-sequence
# budget is the derived quantity and it is what is pinned across rungs. Raising
# --parallel without raising --ctx-size shortens every sequence and would show
# up as c3_rag failing rather than as a slow config.
set -euo pipefail

llama-server \
    --model models/gguf/Qwen_Qwen3-8B-Q4_K_S.gguf \
    --alias qwen3-8b \
    --host 127.0.0.1 \
    --port 8080 \
    --n-gpu-layers 99 \
    --ctx-size 65536 \
    --parallel 8 \
    --batch-size 2048 \
    --ubatch-size 512 \
    --cache-type-k f16 \
    --cache-type-v f16 \
    --threads 20 \
    --seed 0 \
    --metrics \
    --cache-reuse 0 \
    --flash-attn on \
    --no-webui
